transcode_limit: 2
crop_limit: 2
copy_limit: 4
db_path: 'C:\ProgramData\transcodefactory\transcodefactory.db'
ffmpeg_path: 'C:\ffmpeg\ffmpeg.exe'
ffprobe_path: 'C:\ffmpeg\ffprobe.exe'
log_directory: 'C:\ProgramData\transcodefactory\logs'
listen_port: 51218
listen_address: ''